project:
  type: website

website:
  site-url: "https://epiverse-trace.github.io/blog"
  title: "Epiverse-Trace developer space"
  navbar:
    left:
      - text: Software
        href: https://epiverse-trace.r-universe.dev/ui#packages
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/DataDotOrg
  google-analytics: "G-XZ471458FQ"
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
