project:
  type: website

website:
  site-url: "https://epiverse-trace.github.io/"
  title: "Epiverse-TRACE developer space"
  description: "A place for Epiverse-TRACE developers to share their reflections, learnings, and showcase their work."
  navbar:
    left:
      - text: Software
        href: https://epiverse-trace.r-universe.dev/ui#packages
      - blog.qmd
      - presentations.qmd
    right:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/DataDotOrg
  google-analytics: "G-XZ471458FQ"
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
